export const GET_CHARITIES_SUCCESS = 'GET_CHARITIES_SUCCESS';
export const UPDATE_TOTAL_DONATIONS = 'UPDATE_TOTAL_DONATIONS';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

