export const GET_CHARITIES = 'GET_CHARITIES';
export const UPDATE_TOTAL_DONATIONS = 'UPDATE_TOTAL_DONATIONS';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const ERROR_MESSAGE = 'ERROR_MESSAGE';

